### ISSUE TITLE
API example - how to create custom components

### ISSUE THREAD

**Issue by FlorianLudwig** [GreyRook/POM#9]

**Comment by brean** [comment]
move this ticket to POM-examples?

**Comment by FlorianLudwig** [comment]
@brean imho API documentation belongs into this repository

**Comment by FabianElsmer** [comment]
I added an example in the POM Examples readme for now, until we improve our example page / make a better API doc

**Comment by FlorianLudwig** [comment]
moved to POM readme to avoid spreading information to wide

**Comment by brean** [comment]
I think this needs some more documentation, so maybe reopen?
